# Generated by Django 5.1.3 on 2024-11-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('license_plate', models.PositiveIntegerField()),
                ('studentt_name', models.CharField(max_length=100)),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('car_model', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
